### PR TITLE
validate incoming data in network thread

### LINKED ISSUE #417: Memory leak
build iotivity with OC_TCP and connect netcat or similar to the coaps+tcp port
send some data and monitor RSS for the process.
each time any data is sent to the port a message is created and stored internally until the connection is closed.
keep the conneciton open and send anough data and there will eventually be a OOM event.

tcpsession.c:186 (null) new TCP session endpoint: coap+tcp://10.210.48.50:53228, endpoint interface: 2, sock: 28, connected: 1

the following is part of the logging for each message received, since it wasn't a valid coap message it should just have been discarded.

processing 1 events
tcpsession.c:454 (null) tcp receive session(fd=28)
tcpsession.c:411 (null) recv(): 6 bytes.
message_length : 6, num_extended_length_bytes : 0
tcpsession.c:426 (null) tcp packet total length : 13 bytes.
tcpsession.c:411 (null) recv(): 7 bytes.
Inbound network event: decrypted request
CoAP Engine: received datalen=13 from
message_length : 6, num_extended_length_bytes : 0
Token (len 5)
OPTION 3 (delta 3, len 4):
Uri-Host [fwö]
OPTION 9 (delta 6, len 3):
Unsupported option
coap_oscore_parse_options failed!
Unexpected CoAP command
processing 1 events
tcpsession.c:454 (null) tcp receive session(fd=28)
tcpsession.c:411 (null) recv(): 1 bytes.
cbor encoder buffer was shrinked from 262144 to 295
oc_store: encoded ael size 295
audit_log: COMM-1 Unexpected CoAP command 64 2; status = 1
CoAP send empty message: mid=0, code=130
message_length : 0, num_extended_length_bytes : 0
tcpsession.c:426 (null) tcp packet total length : 12 bytes.
Calculating size of options
-Serializing MID 0 to 0xf7a12010
Token (len 5)
Serializing options at 0xf7a12019
Serialize content format: 0
-Done serializing at 0xf7a12019----
Serialized payload:
-Done 9 B (header len 9, payload len 0)-
Dump
-sending OCF message (9)-
Outbound network event: unicast message

### PR DESCRIPTION
**Pull request by jkralik**
The network thread will now perform a validation check on incoming data via TCP/UDP. Any data that fails the validation check will result in the termination of the connection for TCP or dropping message for UDP.

Fixes #417

### CODE REVIEW

File: api/oc_network_events.c [hunk 1]
```diff
@@ -91,6 +93,17 @@ OC_PROCESS_THREAD(oc_network_events, ev, data)
...
+  }
+  // validate UDP/DTLS message, TCP messages is validated directly in the port
+  // layer for closing the connection
+  if (((message->endpoint.flags & TCP) == 0) &&
+      !oc_udp_is_valid_header(message, &message->endpoint)) {
+    OC_ERR("invalid header - dropping message");
+    oc_message_unref(message);
+    return;
+  }
   if (!oc_process_is_running(&oc_network_events)) {
```
Comment (Danielius1922) [inline api/oc_network_events.c:107]: I would move this check before checking of the header (line 99)

Comment (Danielius1922) [inline api/oc_network_events.c:107]: I would move this check before checking of the header (line 99)

File: api/oc_tcp.c [hunk 2]
```diff
@@ -65,3 +74,69 @@ oc_tcp_on_connect_event_free(oc_tcp_on_connect_event_t *event)
...
+      return false;
+    }
+    if (minor_version != MBEDTLS_SSL_MINOR_VERSION_3 &&
+        minor_version != MBEDTLS_SSL_MINOR_VERSION_4 &&
+        // TLS 1.0
+        minor_version != 1 &&
+        // TLS 1.1
+        minor_version != 2) {
+      OC_ERR("invalid minor version: %d", minor_version);
+      // TLS 1.2 and TLS 1.3 are supported
```
Comment (Danielius1922) [inline api/oc_tcp.c:123]: TLS 1.0 and TLS 2.0 are supported too if the comments on lines 118 and 120 are correct

File: api/oc_tcp.c [hunk 3]
```diff
@@ -65,3 +74,69 @@ oc_tcp_on_connect_event_free(oc_tcp_on_connect_event_t *event)
...
+      // Valid record type
+      break;
+    default:
+      OC_ERR("invalid record type: %d", type);
+      // Invalid record type
+      return false;
+    }
+    if (major_version != MBEDTLS_SSL_MAJOR_VERSION_3) {
+      OC_ERR("invalid major version: %d", major_version);
+      // Invalid major version
```
Comment (Danielius1922) [inline api/oc_tcp.c:113]: this line doesn't seem necessary since you have an error with the same text line above

File: api/oc_tcp.c [hunk 4]
```diff
@@ -65,3 +74,69 @@ oc_tcp_on_connect_event_free(oc_tcp_on_connect_event_t *event)
...
+      return false;
+    }
+    return true;
+  }
+#else  /* OC_SECURITY */
+  (void)endpoint;
+#endif /* !OC_SECURITY */
+  int token_len = (COAP_HEADER_TOKEN_LEN_MASK & message->data[0]) >>
+                  COAP_HEADER_TOKEN_LEN_POSITION;
+  if (token_len > 8) {
```
Comment (Danielius1922) [inline api/oc_tcp.c:134]: 8 -> `COAP_TOKEN_LEN` ?

File: port/android/tcpadapter.c [hunk 5]
```diff
@@ -428,6 +436,16 @@ oc_tcp_receive_message(ip_context_t *dev, fd_set *fds, oc_message_t *message)
...
+    if (coap_tcp_parse_message(packet, message->data, message->length, true) !=
+        COAP_NO_ERROR) {
+      OC_ERR("coap_tcp_parse_message error");
+      free_tcp_session(session);
+      return ADAPTER_STATUS_ERROR;
+    }
+  }
+
   memcpy(&message->endpoint, &session->endpoint, sizeof(oc_endpoint_t));
 #ifdef OC_SECURITY
```
Comment (Danielius1922) [inline port/android/tcpadapter.c:450]: If you move lines 450-454 before line 418 then you remove the endpoint argument from the `oc_tcp_is_valid_header` function and just check the `encrypted` member on the `message` argument. 
Same with the check on line `439`.

File: api/oc_network_events.c (hunk 1 above)
Comment (jkralik) [reply api/oc_network_events.c:107]: fixed

File: api/oc_tcp.c (hunk 3 above)
Comment (jkralik) [reply api/oc_tcp.c:113]: removed

File: port/android/tcpadapter.c (hunk 5 above)
Comment (jkralik) [reply port/android/tcpadapter.c:450]: moved

File: api/oc_tcp.c (hunk 4 above)
Comment (jkralik) [reply api/oc_tcp.c:134]: fixed

File: messaging/coap/coap.h [hunk 6]
```diff
@@ -180,12 +180,35 @@ size_t coap_serialize_message(void *packet, uint8_t *buffer);
...
+ * @param data raw message data
+ * @param data_len length of raw message data
+ * @param current_option offset of current option in raw message data
+ * @param inner oscore inner option
+ * @param outer oscore outer option
+ * @param oscore oscore used
+ * @param validate if true, it doesn't modify data
+ * @return coap_status_t
+ */
 coap_status_t coap_oscore_parse_options(void *packet, uint8_t *data,
```
Comment (Danielius1922) [inline messaging/coap/coap.h:197]: If I recall correctly, the headers from `messaging/coap` folders are included in public headers. I suspect that's because they are included in other public headers which use some coap constants and/or types. In which case we should reorganize the library and make public only what's necessary from `messaging/coap`. Right now, everything is public, so all functions are public API functions, which is definitely not right. I'll write down an issue.

File: api/oc_tcp_internal.h [hunk 7]
```diff
@@ -46,10 +47,16 @@ oc_tcp_on_connect_event_t *oc_tcp_on_connect_event_create(
 /** @brief Free TCP on connect event */
 void oc_tcp_on_connect_event_free(oc_tcp_on_connect_event_t *event);
 
+#endif /* OC_HAS_FEATURE_TCP_ASYNC_CONNECT */
+
+/** @brief Check if the message is a valid CoAP/TLS header */
+bool oc_tcp_is_valid_header(const oc_message_t *message);
+
+bool oc_tcp_is_valid_message(const oc_message_t *message);
```
Comment (Danielius1922) [inline api/oc_tcp_internal.h:55]: at least brief docu

File: api/oc_udp.c [hunk 8]
```diff
@@ -0,0 +1,95 @@
...
+#ifdef OC_OSCORE
+  if (oscore_is_oscore_message(message) >= 0) {
+    // it is oscore message
+    return true;
+  }
+#endif /* OC_OSCORE */
+#endif /* OC_SECURITY */
+  coap_packet_t
+    packet[1]; /* this way the packet can be treated as pointer as usual */
+  coap_status_t s = coap_udp_parse_message(packet, (uint8_t *)message->data,
```
Comment (Danielius1922) [inline api/oc_udp.c:88]: given that this is actually parses the whole message, shouldn't this function be called `oc_udp_is_valid_message` ?

File: api/oc_tcp_internal.h (hunk 7 above)
Comment (jkralik) [reply api/oc_tcp_internal.h:55]: fixed

File: api/oc_udp.c (hunk 8 above)
Comment (jkralik) [reply api/oc_udp.c:88]: fixed

File: messaging/coap/coap.c [hunk 9]
```diff
@@ -972,11 +915,107 @@ coap_oscore_parse_options(void *packet, uint8_t *data, uint32_t data_len,
...
+coap_oscore_parse_options(void *packet, uint8_t *data, size_t data_len,
+                          uint8_t *current_option, bool inner, bool outer,
+                          bool oscore, bool validate)
+{
+  if (data_len > UINT32_MAX) {
+    OC_WRN("message size(%zu) exceeds limit for coap message(%u)", data_len,
+           UINT32_MAX);
+    return BAD_REQUEST_4_00;
+  }
+  (void)oscore;
```
[the remark this answers is not in the document]
Comment (jkralik) [reply messaging/coap/coap.c:932]: fixed

File: api/oc_udp.c (hunk 8 above)
Comment (jkralik) [reply api/oc_udp.c:88]: fixed

File: messaging/coap/coap.c [hunk 10]
```diff
@@ -792,6 +726,9 @@ coap_oscore_parse_options(void *packet, uint8_t *data, uint32_t data_len,
       if (!outer) {
         return BAD_OPTION_4_02;
       }
+      if (validate) {
```
[the remark this answers is not in the document]
Comment (jkralik) [reply messaging/coap/coap.c:729]: Yes correcr because it is modified `message->data` buffer

[the remark this answers is not in the document]
Comment (jkralik) [reply messaging/coap/coap.c:729]: readonly?

**Comment by jkralik** [comment]
@SiMet Pls could you check if jenkins works for `OCF Conformance / Test` ? The test has been cancelled after 6hours.

File: api/oc_udp_internal.h [hunk 11]
```diff
@@ -0,0 +1,36 @@
...
+ * either express or implied. See the License for the specific
+ * language governing permissions and limitations under the License.
+ *
+ ****************************************************************************/
+
+#ifndef OC_UDP_INTERNAL_H
+#define OC_UDP_INTERNAL_H
+
+#include "port/oc_connectivity.h"
+#include "oc_endpoint.h"
```
[the remark this answers is not in the document]
Comment (jkralik) [reply api/oc_udp_internal.h:23]: removed

File: api/oc_udp.c [hunk 12]
```diff
@@ -0,0 +1,101 @@
...
+ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
+ * either express or implied. See the License for the specific
+ * language governing permissions and limitations under the License.
+ *
+ ****************************************************************************/
+
+#include "util/oc_features.h"
+#include "messaging/coap/coap.h"
+#include "oc_endpoint.h"
+#include "port/oc_assert.h"
```
[the remark this answers is not in the document]
Comment (jkralik) [reply api/oc_udp.c:22]: removed

File: api/oc_udp.c [hunk 13]
```diff
@@ -0,0 +1,100 @@
...
+#include "messaging/coap/coap.h"
+#include "port/oc_connectivity.h"
+#ifdef OC_SECURITY
+#include <mbedtls/ssl.h>
+#ifdef OC_OSCORE
+#include "messaging/coap/oscore.h"
+#endif /* OC_OSCORE */
+#endif /* OC_SECURITY */
+
+#include <assert.h>
```
Comment (Danielius1922) [inline api/oc_udp.c:31]: assert.h twice, my convention is internal headers in `""` first and then third-party headers in `<>`, so I would remove the include on line 19

Comment (jkralik) [reply api/oc_udp.c:31]: fixed

File: messaging/coap/coap.c (hunk 10 above)
[the remark this answers is not in the document]
Comment (Danielius1922) [reply messaging/coap/coap.c:729]: we will have to make it more readable at some point, I'm sure SC is complaining about its complexity

**Comment by Danielius1922** [comment]
There are two `redundant cast` and one change param to `const` in SC that should be easily fixable, no?
